// Cart Operations
export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const CLEAR_CART_REQUEST = 'CLEAR_CART_REQUEST';
export const CLEAR_CART_SUCCESS = 'CLEAR_CART_SUCCESS';
export const CLEAR_CART_FAILURE = 'CLEAR_CART_FAILURE';

export const CALCULATE_CART_TOTAL_REQUEST = 'CALCULATE_CART_TOTAL_REQUEST';
export const CALCULATE_CART_TOTAL_SUCCESS = 'CALCULATE_CART_TOTAL_SUCCESS';
export const CALCULATE_CART_TOTAL_FAILURE = 'CALCULATE_CART_TOTAL_FAILURE';

// Cart Item Operations
export const UPDATE_CART_ITEM_REQUEST = 'UPDATE_CART_ITEM_REQUEST';
export const UPDATE_CART_ITEM_SUCCESS = 'UPDATE_CART_ITEM_SUCCESS';
export const UPDATE_CART_ITEM_FAILURE = 'UPDATE_CART_ITEM_FAILURE';

export const REMOVE_CART_ITEM_REQUEST = 'REMOVE_CART_ITEM_REQUEST';
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';
export const REMOVE_CART_ITEM_FAILURE = 'REMOVE_CART_ITEM_FAILURE'; 

export const SET_DELIVERY_TYPE_REQUEST = 'SET_DELIVERY_TYPE_REQUEST';
export const SET_DELIVERY_TYPE_SUCCESS = 'SET_DELIVERY_TYPE_SUCCESS';
export const SET_DELIVERY_TYPE_FAILURE = 'SET_DELIVERY_TYPE_FAILURE';