export const FETCH_INGREDIENTS_REQUEST = 'FETCH_INGREDIENTS_REQUEST';
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_FAILURE = 'FETCH_INGREDIENTS_FAILURE';

export const ADD_INGREDIENT_REQUEST = 'ADD_INGREDIENT_REQUEST';
export const ADD_INGREDIENT_SUCCESS = 'ADD_INGREDIENT_SUCCESS';
export const ADD_INGREDIENT_FAILURE = 'ADD_INGREDIENT_FAILURE';

export const UPDATE_INGREDIENT_REQUEST = 'UPDATE_INGREDIENT_REQUEST';
export const UPDATE_INGREDIENT_SUCCESS = 'UPDATE_INGREDIENT_SUCCESS';
export const UPDATE_INGREDIENT_FAILURE = 'UPDATE_INGREDIENT_FAILURE';

export const DELETE_INGREDIENT_REQUEST = 'DELETE_INGREDIENT_REQUEST';
export const DELETE_INGREDIENT_SUCCESS = 'DELETE_INGREDIENT_SUCCESS';
export const DELETE_INGREDIENT_FAILURE = 'DELETE_INGREDIENT_FAILURE'; 