// Restaurant List Actions
export const FETCH_RESTAURANTS_REQUEST = 'FETCH_RESTAURANTS_REQUEST';
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_FAILURE = 'FETCH_RESTAURANTS_FAILURE';

// Single Restaurant Actions
export const FETCH_RESTAURANT_REQUEST = 'FETCH_RESTAURANT_REQUEST';
export const FETCH_RESTAURANT_SUCCESS = 'FETCH_RESTAURANT_SUCCESS';
export const FETCH_RESTAURANT_FAILURE = 'FETCH_RESTAURANT_FAILURE';

// Restaurant Owner Actions
export const FETCH_MY_RESTAURANT_REQUEST = 'FETCH_MY_RESTAURANT_REQUEST';
export const FETCH_MY_RESTAURANT_SUCCESS = 'FETCH_MY_RESTAURANT_SUCCESS';
export const FETCH_MY_RESTAURANT_FAILURE = 'FETCH_MY_RESTAURANT_FAILURE';

// Create Restaurant Actions
export const CREATE_RESTAURANT_REQUEST = 'CREATE_RESTAURANT_REQUEST';
export const CREATE_RESTAURANT_SUCCESS = 'CREATE_RESTAURANT_SUCCESS';
export const CREATE_RESTAURANT_FAILURE = 'CREATE_RESTAURANT_FAILURE';

// Update Restaurant Actions
export const UPDATE_RESTAURANT_REQUEST = 'UPDATE_RESTAURANT_REQUEST';
export const UPDATE_RESTAURANT_SUCCESS = 'UPDATE_RESTAURANT_SUCCESS';
export const UPDATE_RESTAURANT_FAILURE = 'UPDATE_RESTAURANT_FAILURE';

// Delete Restaurant Actions
export const DELETE_RESTAURANT_REQUEST = 'DELETE_RESTAURANT_REQUEST';
export const DELETE_RESTAURANT_SUCCESS = 'DELETE_RESTAURANT_SUCCESS';
export const DELETE_RESTAURANT_FAILURE = 'DELETE_RESTAURANT_FAILURE';

// Search Restaurant Actions
export const SEARCH_RESTAURANTS_REQUEST = 'SEARCH_RESTAURANTS_REQUEST';
export const SEARCH_RESTAURANTS_SUCCESS = 'SEARCH_RESTAURANTS_SUCCESS';
export const SEARCH_RESTAURANTS_FAILURE = 'SEARCH_RESTAURANTS_FAILURE';

// Favourite Restaurant Actions
export const ADD_TO_FAVOURITE_REQUEST = 'ADD_TO_FAVOURITE_REQUEST';
export const ADD_TO_FAVOURITE_SUCCESS = 'ADD_TO_FAVOURITE_SUCCESS';
export const ADD_TO_FAVOURITE_FAILURE = 'ADD_TO_FAVOURITE_FAILURE';

// Restaurant Status Actions
export const UPDATE_RESTAURANT_STATUS_REQUEST = 'UPDATE_RESTAURANT_STATUS_REQUEST';
export const UPDATE_RESTAURANT_STATUS_SUCCESS = 'UPDATE_RESTAURANT_STATUS_SUCCESS';
export const UPDATE_RESTAURANT_STATUS_FAILURE = 'UPDATE_RESTAURANT_STATUS_FAILURE';

// Restaurant Rating Actions
export const UPDATE_RESTAURANT_RATING_REQUEST = 'UPDATE_RESTAURANT_RATING_REQUEST';
export const UPDATE_RESTAURANT_RATING_SUCCESS = 'UPDATE_RESTAURANT_RATING_SUCCESS';
export const UPDATE_RESTAURANT_RATING_FAILURE = 'UPDATE_RESTAURANT_RATING_FAILURE';

// Restaurant Orders Actions
export const FETCH_RESTAURANT_ORDERS_REQUEST = 'FETCH_RESTAURANT_ORDERS_REQUEST';
export const FETCH_RESTAURANT_ORDERS_SUCCESS = 'FETCH_RESTAURANT_ORDERS_SUCCESS';
export const FETCH_RESTAURANT_ORDERS_FAILURE = 'FETCH_RESTAURANT_ORDERS_FAILURE';

// Update Order Status Actions
export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE'; 