// Menu Action Types
export const FETCH_MENU_REQUEST = 'FETCH_MENU_REQUEST';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAILURE = 'FETCH_MENU_FAILURE';

// Additional action types for menu items
export const FETCH_MENU_ITEMS_REQUEST = 'FETCH_MENU_ITEMS_REQUEST';
export const FETCH_MENU_ITEMS_SUCCESS = 'FETCH_MENU_ITEMS_SUCCESS';
export const FETCH_MENU_ITEMS_FAILURE = 'FETCH_MENU_ITEMS_FAILURE';

export const ADD_MENU_ITEM_REQUEST = 'ADD_MENU_ITEM_REQUEST';
export const ADD_MENU_ITEM_SUCCESS = 'ADD_MENU_ITEM_SUCCESS';
export const ADD_MENU_ITEM_FAILURE = 'ADD_MENU_ITEM_FAILURE';

export const CREATE_MENU_ITEM_REQUEST = 'CREATE_MENU_ITEM_REQUEST';
export const CREATE_MENU_ITEM_SUCCESS = 'CREATE_MENU_ITEM_SUCCESS';
export const CREATE_MENU_ITEM_FAILURE = 'CREATE_MENU_ITEM_FAILURE';

export const UPDATE_MENU_ITEM_REQUEST = 'UPDATE_MENU_ITEM_REQUEST';
export const UPDATE_MENU_ITEM_SUCCESS = 'UPDATE_MENU_ITEM_SUCCESS';
export const UPDATE_MENU_ITEM_FAILURE = 'UPDATE_MENU_ITEM_FAILURE';

export const DELETE_MENU_ITEM_REQUEST = 'DELETE_MENU_ITEM_REQUEST';
export const DELETE_MENU_ITEM_SUCCESS = 'DELETE_MENU_ITEM_SUCCESS';
export const DELETE_MENU_ITEM_FAILURE = 'DELETE_MENU_ITEM_FAILURE';

export const SEARCH_MENU_ITEMS_REQUEST = 'SEARCH_MENU_ITEMS_REQUEST';
export const SEARCH_MENU_ITEMS_SUCCESS = 'SEARCH_MENU_ITEMS_SUCCESS';
export const SEARCH_MENU_ITEMS_FAILURE = 'SEARCH_MENU_ITEMS_FAILURE';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

export const UPDATE_ITEM_AVAILABILITY_REQUEST = 'UPDATE_ITEM_AVAILABILITY_REQUEST';
export const UPDATE_ITEM_AVAILABILITY_SUCCESS = 'UPDATE_ITEM_AVAILABILITY_SUCCESS';
export const UPDATE_ITEM_AVAILABILITY_FAILURE = 'UPDATE_ITEM_AVAILABILITY_FAILURE';

export const SET_CURRENT_MENU_ITEM = 'SET_CURRENT_MENU_ITEM';
export const CLEAR_CURRENT_MENU_ITEM = 'CLEAR_CURRENT_MENU_ITEM'; 